-- CreateEnum
CREATE TYPE "AccionAuditoria" AS ENUM ('CREAR_USUARIO', 'MODIFICAR_USUARIO', 'DESACTIVAR_USUARIO', 'ACTIVAR_USUARIO', 'CAMBIAR_PASSWORD', 'RESETEAR_PASSWORD', 'LOGIN_EXITOSO', 'LOGIN_FALLIDO', 'LOGOUT', 'SESION_EXPIRADA', 'CREAR_PRACTICA', 'MODIFICAR_PRACTICA', 'ANULAR_PRACTICA', 'CAMBIAR_ESTADO_PRACTICA', 'ASIGNAR_DOCENTE_PRACTICA', 'CAMBIAR_DOCENTE_PRACTICA', 'COMPLETAR_ACTA1_COORDINADOR', 'COMPLETAR_ACTA1_ALUMNO', 'ACEPTAR_ACTA1_DOCENTE', 'RECHAZAR_ACTA1_DOCENTE', 'GENERAR_ACTA_FINAL', 'VALIDAR_ACTA_FINAL', 'CERRAR_ACTA_FINAL', 'CREAR_EVALUACION_INFORME', 'MODIFICAR_EVALUACION_INFORME', 'COMPLETAR_EVALUACION_INFORME', 'CREAR_EVALUACION_EMPLEADOR', 'MODIFICAR_EVALUACION_EMPLEADOR', 'COMPLETAR_EVALUACION_EMPLEADOR', 'CALCULAR_NOTA_FINAL', 'SUBIR_INFORME_PRACTICA', 'MODIFICAR_INFORME_PRACTICA', 'ELIMINAR_INFORME_PRACTICA', 'SUBIR_DOCUMENTO_APOYO', 'MODIFICAR_DOCUMENTO_APOYO', 'ELIMINAR_DOCUMENTO_APOYO', 'DESCARGAR_DOCUMENTO', 'CREAR_CENTRO_PRACTICA', 'MODIFICAR_CENTRO_PRACTICA', 'DESACTIVAR_CENTRO_PRACTICA', 'ASOCIAR_EMPLEADOR_CENTRO', 'DESASOCIAR_EMPLEADOR_CENTRO', 'CREAR_CARRERA', 'MODIFICAR_CARRERA', 'DESACTIVAR_CARRERA', 'CREAR_SEDE', 'MODIFICAR_SEDE', 'DESACTIVAR_SEDE', 'ASOCIAR_DOCENTE_CARRERA', 'DESASOCIAR_DOCENTE_CARRERA', 'GENERAR_ALERTA_MANUAL', 'ENVIAR_NOTIFICACION_EMAIL', 'GENERAR_ALERTA_AUTOMATICA', 'MODIFICAR_CONFIG_EVALUACION', 'MODIFICAR_PARAMETROS_SISTEMA', 'GENERAR_REPORTE', 'EXPORTAR_DATOS', 'CONSULTAR_HISTORIALES', 'BACKUP_BASE_DATOS', 'RESTAURAR_BASE_DATOS', 'MANTENIMIENTO_SISTEMA');

-- CreateTable
CREATE TABLE "LogAuditoria" (
    "id" SERIAL NOT NULL,
    "accion" "AccionAuditoria" NOT NULL,
    "entidad" TEXT NOT NULL,
    "entidadId" TEXT NOT NULL,
    "usuarioId" INTEGER NOT NULL,
    "descripcion" TEXT,
    "detallesPrevios" JSONB,
    "detallesNuevos" JSONB,
    "metadatos" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "fecha" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LogAuditoria_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "LogAuditoria_entidad_entidadId_idx" ON "LogAuditoria"("entidad", "entidadId");

-- CreateIndex
CREATE INDEX "LogAuditoria_usuarioId_idx" ON "LogAuditoria"("usuarioId");

-- CreateIndex
CREATE INDEX "LogAuditoria_accion_idx" ON "LogAuditoria"("accion");

-- CreateIndex
CREATE INDEX "LogAuditoria_fecha_idx" ON "LogAuditoria"("fecha");

-- CreateIndex
CREATE INDEX "LogAuditoria_entidad_accion_idx" ON "LogAuditoria"("entidad", "accion");

-- AddForeignKey
ALTER TABLE "LogAuditoria" ADD CONSTRAINT "LogAuditoria_usuarioId_fkey" FOREIGN KEY ("usuarioId") REFERENCES "Usuario"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
